name: Check Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Verificar cambios en archivos
        run: echo "Pull Request detectado en $(date)"
